### ISSUE TITLE
Add Shop name page; Unique Shop Name Text Displays as Help Note in Grey 

### ISSUE THREAD

**Issue by abhilla** [zite69/shop-cms#27]
Unique Shop Name Text Displays as Help Note in Grey and italics.
It has to appear like normal text question other text like GST Number etc.
![Unique Shopt Name appearing as help note format in add shop name page ](https://github.com/user-attachments/assets/3e801da6-1b9d-45d2-85b7-caf35a336b3d)

**Comment by arunk** [comment]
@abhilla please check and see if this is fixed in beta. also please check all the other Seller Registration form texts. I have set only pincode text to gray and italics. Everything else I have set back to what it was.

**Comment by abhilla** [comment]
Verified Fixed Commit @Commit 12de18a
